### ISSUE TITLE
Rename folders

### ISSUE THREAD

**Issue by walbo** [DekodeInteraktiv/teft-base#25]
1. Rename `web` to `public`. If we do this we can clone the repo into Local By Flywheels app folder and everything will work without doing all the post install script stuff.
2. Rename the `app` folder inside `web` to `content`. We have used `content` for years. Not sure why we have called in `app` here?

**Comment by henningdekode** [comment]
We can make this change as long as we make sure to upgrade the version to a major so it does not break older projects
