### ISSUE TITLE
Replace codeship with github actions

### ISSUE THREAD

**Issue by zpaceinvader** [DekodeInteraktiv/teft-base#399]
Remove codeship-related code and add necessary github actions code

**Comment by olethomas** [comment]
What is needed to take this one further from your side, @dekode-andre?

**Comment by dekode-andre** [comment]
There's currently two Wireguard related issues that blocks widespread use of Github Actions for all projects. Either these have to be fixed, worked around or we need another way to securely connect to our servers from the workflows. These issues requires custom VPN configs set up for every project and is therefore really bad for automation and standardization. 

- There is no dynamic IP allocation for connecting clients. So currently a new peer-configuration has to be set up on the wireguard server, which implies a new VPN client configuration, with a specific client IP address set. This config can be used for only one connecting client, or we will face IP address conflicts and strange behaviour.
- We cannot set the VPN client to route all traffic over the VPN. This breaks the connection with Github itself and crashes the workflows. This means we have to specify the server IP to which the workflow wishes to deploy in each config.

**Comment by henningdekode** [comment]
@dekode-andre and @Clorith we discussed this and from what I understood we have a possible fix for this?
