### ISSUE TITLE
Theme settings filters not working

### ISSUE THREAD

**Issue by rwrobe** [DekodeInteraktiv/teft-base#47]
Ran into an issue where trying to filter the menus in the header and footer didn't change the menu locations in the theme. The following code does not affect whether or not the footer menu is registered:

```
function remove_footer_menu(): array {
		return [];
	}

add_filter( 'teft_footer_menus', __NAMESPACE__ . '\\remove_footer_menu', 10, 1 );
```

Checked Thongruppen because their repo had this code as well and the footer menu still displays on  dev03.

**Comment by olethomas** [comment]
Closing this as it is not related to the base setup.
